import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen flex flex-col"
      >
        <header className="bg-slate-900 text-white p-4 text-center">
          <p>moi</p>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="bg-slate-900 text-white p-4 text-center">
          <p>pöö</p>
        </footer>
      </body>
    </html>
  );
}
